fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: public
    user_class: Mii\GameBundle\Entity\User
    
fos_facebook:
     file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
     alias:  facebook
     app_id: 145597308865831
     secret: e2b541a0623613634f753d044638367d
     cookie: true
     permissions: [email, user_birthday, user_location, publish_stream]
     
services:
    my.facebook.user:
        class: Mii\GameBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"