fos_facebook:
     file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
     alias:  facebook
     app_id: 123456879
     secret: s3cr3t
     cookie: true
     permissions: [email, user_birthday, user_location]