_security_check:
    pattern:  /login_check
_security_logout:
    pattern:  /logout  
      
MiiGameBundle:
    resource: "@MiiGameBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
