security:
     factories:
         - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"

     providers:
         fos_facebook:
             id: fos_facebook.auth

     firewalls:
         public:
              # since anonymous is allowed users will not be forced to login
             pattern:   ^/.*
             fos_facebook:
                 app_url: "http://apps.facebook.com/buscalasdiferencias/"
                 server_url: "http://mallify.com/diferencias/web/"
             anonymous: true
             logout:
                 handlers: ["fos_facebook.logout_handler"]

     access_control:
      #   - { path: ^/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
         - { path: ^/login.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }